### ISSUE TITLE
奈良県版用のエクセルjson変換ツールの作成

### ISSUE THREAD

**Issue by YasushiIS** [code4nara/covid19-nara-tools#1]
奈良県版用のエクセルjson変換ツールの作成

奈良県からエクセルもしくはcsvが提供されるようになってから作成。

**Comment by imabari** [comment]
奈良県_新型コロナウイルス感染症について
http://www.pref.nara.jp/55168.htm

上記データからdata.jsonを作成しています

https://github.com/imabari/covid19-data/blob/master/nara/main.py

**Comment by YasushiIS** [comment]
convert_naraprefV3.py として作成し本番サイトでの動作確認もできたのでクローズします。
